modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/RedCraft86/RedPackUtils/issues"
#clientSideOnly=true # defaults to false if absent

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/RedCraft86/RedPackUtils"
logoFile="logo.png"
authors="${mod_authors}"
description='''${mod_description}'''
#updateJSONURL=""
#credits=""

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[modproperties.${mod_id}]
catalogueImageIcon = "logo.png"